import type { Product, Category, User, Order } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) return { imageUrl: 'https://picsum.photos/seed/placeholder/400/400', imageHint: 'placeholder' };
  return { imageUrl: image.imageUrl, imageHint: image.imageHint };
}

export const CATEGORIES: Category[] = [
  { id: 'cpu', name: 'Processors (CPU)' },
  { id: 'ram', name: 'Memory (RAM)' },
  { id: 'gpu', name: 'Graphics Cards' },
  { id: 'storage', name: 'Storage' },
  { id: 'motherboards', name: 'Motherboards' },
  { id: 'psu', name: 'Power Supplies' },
  { id: 'sbc', name: 'Single-Board Computers' },
  { id: 'sensors', name: 'Sensors' },
  { id: 'modules', name: 'Modules' },
  { id: 'ics', name: 'Integrated Circuits' },
  { id: 'passive', name: 'Passive Components' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'QuantumCore Q9 Processor',
    slug: 'quantumcore-q9-processor',
    description: 'The latest generation 16-core processor for ultimate performance in gaming and professional workloads.',
    price: 599.99,
    stock: 50,
    category: CATEGORIES[0],
    specifications: { 'Cores': '16', 'Threads': '32', 'Boost Clock': '5.8 GHz', 'TDP': '150W' },
    ...findImage('product-cpu'),
  },
  {
    id: '2',
    name: 'AetherRAM 32GB DDR5 Kit',
    slug: 'aetherram-32gb-ddr5-kit',
    description: 'High-speed DDR5 memory kit (2x16GB) running at 6000MHz, perfect for modern systems.',
    price: 129.99,
    stock: 150,
    category: CATEGORIES[1],
    specifications: { 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6000', 'CAS Latency': '36' },
    ...findImage('product-ram'),
  },
  {
    id: '3',
    name: 'NebulaRender RTX 5090',
    slug: 'nebularender-rtx-5090',
    description: 'Top-of-the-line graphics card for 4K ray-traced gaming and professional rendering.',
    price: 1999.99,
    stock: 25,
    category: CATEGORIES[2],
    specifications: { 'Memory': '24GB GDDR7', 'Boost Clock': '3.2 GHz', 'Power Connectors': '1x 16-pin' },
    ...findImage('product-gpu'),
  },
  {
    id: '4',
    name: 'Singularity SSD 4TB NVMe',
    slug: 'singularity-ssd-4tb-nvme',
    description: 'Blazing fast Gen5 NVMe SSD with read speeds up to 12,000 MB/s.',
    price: 349.99,
    stock: 80,
    category: CATEGORIES[3],
    specifications: { 'Capacity': '4TB', 'Interface': 'PCIe 5.0 x4', 'Read Speed': '12,000 MB/s' },
    ...findImage('product-ssd'),
  },
  {
    id: '5',
    name: 'Cosmos Z990 Motherboard',
    slug: 'cosmos-z990-motherboard',
    description: 'A feature-rich motherboard for the latest processors, with Wi-Fi 7 and PCIe 5.0 support.',
    price: 499.99,
    stock: 40,
    category: CATEGORIES[4],
    specifications: { 'Form Factor': 'ATX', 'Chipset': 'Z990', 'RAM Slots': '4x DDR5' },
    ...findImage('product-motherboard'),
  },
  {
    id: '6',
    name: 'Volt-Masta 1200W Platinum PSU',
    slug: 'volt-masta-1200w-platinum-psu',
    description: 'Fully modular 1200W power supply with 80+ Platinum efficiency for stable power delivery.',
    price: 249.99,
    stock: 60,
    category: CATEGORIES[5],
    specifications: { 'Wattage': '1200W', 'Efficiency': '80+ Platinum', 'Modularity': 'Fully Modular' },
    ...findImage('product-psu'),
  },
  {
    id: '7',
    name: 'AtmoSense DHT22 Sensor',
    slug: 'atmosense-dht22-sensor',
    description: 'Reliable and accurate temperature and humidity sensor for your DIY electronics projects.',
    price: 9.99,
    stock: 500,
    category: CATEGORIES[7],
    specifications: { 'Type': 'Temperature & Humidity', 'Interface': '1-Wire', 'Accuracy': '±0.5°C, ±2% RH' },
    ...findImage('product-sensor'),
  },
  {
    id: '8',
    name: 'Connecta-Fi ESP32-S3 Module',
    slug: 'connecta-fi-esp32-s3-module',
    description: 'Powerful and versatile ESP32-S3 module with Wi-Fi, Bluetooth 5 (LE), and ample GPIOs.',
    price: 14.99,
    stock: 300,
    category: CATEGORIES[8],
    specifications: { 'MCU': 'ESP32-S3', 'Wi-Fi': '802.11b/g/n', 'Bluetooth': '5.0 LE' },
    ...findImage('product-module'),
  },
  {
    id: '9',
    name: 'LogicGate 555 Timer IC',
    slug: 'logicgate-555-timer-ic',
    description: 'The classic and versatile 555 timer IC, a must-have for any electronics enthusiast. (10-pack)',
    price: 4.99,
    stock: 1000,
    category: CATEGORIES[9],
    specifications: { 'Type': 'Timer', 'Package': 'DIP-8', 'Quantity': '10' },
    ...findImage('product-ic'),
  },
  {
    id: '10',
    name: 'OhmGuard Resistor Kit',
    slug: 'ohmguard-resistor-kit',
    description: 'A comprehensive kit of 500 carbon-film resistors with various common values.',
    price: 19.99,
    stock: 200,
    category: CATEGORIES[10],
    specifications: { 'Type': 'Carbon Film', 'Quantity': '500 pieces', 'Tolerance': '5%' },
    ...findImage('product-resistor-kit'),
  },
  {
    id: '11',
    name: 'ChargeWell Capacitor Kit',
    slug: 'chargewell-capacitor-kit',
    description: 'An assortment of 200 electrolytic capacitors in various voltage and capacitance ratings.',
    price: 24.99,
    stock: 3,
    category: CATEGORIES[10],
    specifications: { 'Type': 'Electrolytic', 'Quantity': '200 pieces', 'Voltage Range': '10V-50V' },
    ...findImage('product-capacitor-kit'),
  },
  {
    id: '12',
    name: 'BerryBoard Pi 5 8GB',
    slug: 'berryboard-pi-5-8gb',
    description: 'The latest single-board computer, offering desktop-level performance in a tiny package.',
    price: 80.00,
    stock: 95,
    category: CATEGORIES[6],
    specifications: { 'RAM': '8GB LPDDR4X', 'CPU': 'Quad-core Cortex-A76', 'Connectivity': 'Wi-Fi 5, Gigabit Ethernet' },
    ...findImage('product-raspberry-pi'),
  },
];

export const USERS: User[] = [
    { id: '1', name: 'Admin', email: 'admin@techzone.com', role: 'admin', createdAt: new Date('2023-01-15') },
    { id: '2', name: 'Alice', email: 'alice@example.com', role: 'customer', createdAt: new Date('2023-02-20') },
    { id: '3', name: 'Bob', email: 'bob@example.com', role: 'customer', createdAt: new Date('2023-03-10') },
    { id: '4', name: 'Charlie', email: 'charlie@example.com', role: 'customer', createdAt: new Date('2023-04-05') },
];

export const ORDERS: Order[] = [
  {
    id: 'ORD001',
    customerName: 'Alice',
    customerEmail: 'alice@example.com',
    items: [
      { productId: '7', productName: 'AtmoSense DHT22 Sensor', quantity: 5, price: 9.99 },
      { productId: '8', productName: 'Connecta-Fi ESP32-S3 Module', quantity: 2, price: 14.99 },
    ],
    total: 79.93,
    status: 'Delivered',
    createdAt: new Date('2023-10-25'),
  },
  {
    id: 'ORD002',
    customerName: 'Bob',
    customerEmail: 'bob@example.com',
    items: [
      { productId: '3', productName: 'NebulaRender RTX 5090', quantity: 1, price: 1999.99 },
    ],
    total: 1999.99,
    status: 'Shipped',
    createdAt: new Date('2023-10-28'),
  },
  {
    id: 'ORD003',
    customerName: 'Charlie',
    customerEmail: 'charlie@example.com',
    items: [
      { productId: '11', productName: 'ChargeWell Capacitor Kit', quantity: 1, price: 24.99 },
      { productId: '10', productName: 'OhmGuard Resistor Kit', quantity: 1, price: 19.99 },
    ],
    total: 44.98,
    status: 'Pending',
    createdAt: new Date(),
  },
    {
    id: 'ORD004',
    customerName: 'Alice',
    customerEmail: 'alice@example.com',
    items: [
      { productId: '12', productName: 'BerryBoard Pi 5 8GB', quantity: 1, price: 80.00 },
    ],
    total: 80.00,
    status: 'Cancelled',
    createdAt: new Date('2023-09-15'),
  },
];
